[package]
name = "nala"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-protocol = { path = "../../crates/agent-protocol" }
chrono = { workspace = true }
csv = "1"
device-capabilities = { path = "../../crates/device-capabilities" }
device-protocol = { path = "../../crates/device-protocol" }
mcp = { path = "../../crates/mcp" }
process-group = { path = "../../crates/process-group" }
reedline = "0.38"
regex = { workspace = true }
reqwest = { workspace = true }
schemars = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tungstenite = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
