[package]
name = "nala"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1"
mcp = { path = "../../crates/mcp" }
process-group = { path = "../../crates/process-group" }
reedline = "0.38"
reqwest = { workspace = true }
schemars = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
