[package]
name = "nala-overlay"
version = "0.1.0"
edition = "2024"

[dependencies]
device-protocol = { path = "../../crates/device-protocol" }
eframe = { version = "0.28", default-features = false, features = [
    "default_fonts",
    "glow",
] }
egui = "0.28"
serde_json = { workspace = true }
tungstenite = { workspace = true }
